/**
 * Checklist
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AnswerType2 = 'None' | 'FreeTextAndJustification' | 'FreeText';

export const AnswerType2 = {

    None: 'None' as AnswerType2,

    FreeTextAndJustification: 'FreeTextAndJustification' as AnswerType2,

    FreeText: 'FreeText' as AnswerType2
};

