/**
 * Checklist
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AnswerType3 = 'None' | 'FreeTextAndJustification' | 'FreeText';

export const AnswerType3 = {

    None: 'None' as AnswerType3,

    FreeTextAndJustification: 'FreeTextAndJustification' as AnswerType3,

    FreeText: 'FreeText' as AnswerType3
};

