/**
 * Checklist
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Url } from './url';


export interface ConferenceInstance2 { 
    id?: string | null;
    year: number;
    url: Array<Url>;
}

