/**
 * Checklist
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Conference2 } from './conference2';


export interface ConferenceInstance3 { 
    year: number;
    conference: Conference2;
}

