/**
 * Checklist
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnswerType3 } from './answer-type3';


export interface SavedQuestion2 { 
    question: string;
    answerType: AnswerType3;
}
export namespace SavedQuestion2 {
}


