/**
 * Checklist
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SavedQuestionOriginalQuestion } from './saved-question-original-question';
import { AnswerType2 } from './answer-type2';


export interface SavedQuestion { 
    id?: string | null;
    question: string;
    answerType: AnswerType2;
    originalQuestion?: SavedQuestionOriginalQuestion | null;
}
export namespace SavedQuestion {
}


