/**
 * Checklist
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Question2 } from './question2';


/**
 * @type SavedQuestionOriginalQuestion
 * @export
 */
export type SavedQuestionOriginalQuestion = Question2;

