/**
 * Checklist
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SaveQuestionRequest } from './save-question-request';


export interface SaveChecklistRequest { 
    uuid?: string | null;
    name: string;
    questionRequests: Array<SaveQuestionRequest>;
}

