/**
 * Checklist
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SavedQuestion } from './saved-question';


export interface SavedChecklist { 
    id?: string | null;
    name: string;
    questions: Array<SavedQuestion>;
    description: string;
}

