/**
 * Checklist
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AnswerType3 = 'None' | 'FreeTextAndJustification' | 'FreeText';

export const AnswerType3 = {
    None: 'None' as AnswerType3,
    FreeTextAndJustification: 'FreeTextAndJustification' as AnswerType3,
    FreeText: 'FreeText' as AnswerType3
};

