/**
 * Checklist
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnswerType3 } from './answer-type3';


export interface SavedQuestion2 { 
    question: string;
    answerType: AnswerType3;
}
export namespace SavedQuestion2 {
}


